language: c
env:
    - OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0
notifications:
    email:
        - rapidlang@googlegroups.com
before_script:
    - bash -ex config/travis_install.sh
    - sudo apt-get install golang
script:
    - cd compiler && make
    - make parser
    - make test
    - yacc -v parser.mly || true    # print the YACC output so we're aware of it
    - ./rapid < tests/sast/int_decl.rapid

